### PR TITLE
Startpage (index) with toprated/upcoming movies

### PR DESCRIPTION
**Pull request by rasmusbaeckstrom**
1. /app/page.tsx (index) contains TopRatedMovies and UpcomingMovies.

2. TopRatedMovies and UpcomingMovies is imported from app/ui/.

3. function TopRatedMovies gets the data from getTopRatedMovies and UpcomingMovies is similiar.

4. getTopRatedMovies and getUpcomingMovies is located in app/lib/data.ts and fetches data from database. 

image

image

### CODE REVIEW

**Comment by MikaelaMathisson** [comment]
Great work Rasmus!! Looks great. Your code looks good so far but I know you had some problems that you are working on. 
I was thinking about the space between the popular and the upcoming movies. Maybe put them a bit closer to each other to not have as much blank space? Just a thought, let me know what you think.

**Review by sebastianpiresmolin — APPROVED** [review]
Nice job! I especially like the solution you've implemented to decide whether a movie is upcoming or currently screening. Will definitively steal that! ;) 

I'm going to steal your card design for /movies so that we can keep a consistent design.

**Comment by rasmusbaeckstrom** [comment]
> Great work Rasmus!! Looks great. Your code looks good so far but I know you had some problems that you are working on. I was thinking about the space between the popular and the upcoming movies. Maybe put them a bit closer to each other to not have as much blank space? Just a thought, let me know what you think.

Thank you! Yepp, thats right! I think youre right, i will make som adjustments! thanks for the input :)

**Comment by rasmusbaeckstrom** [comment]
> Nice job! I especially like the solution you've implemented to decide whether a movie is upcoming or currently screening. Will definitively steal that! ;)
> 
> I'm going to steal your card design for /movies so that we can keep a consistent design.

Thank you! Ofc, go ahead and steal it!

**Pull request merged**
