### PR TITLE
User page

### PR DESCRIPTION
**Pull request by HannaRosberg**
made the userpage and some styling to it

### CODE REVIEW

**Comment by Willi86** [comment]
I still see this message "GitGuardian Security Checks -2 secrets uncovered! " . or is it for the old commit? 
is there a way to avoid this message?  is it possible to remove the branch and commit a new one?

**Comment by sebastianpiresmolin** [comment]
@Willi86 I think what we're going to do is merge this even with the warning and then change the keys on Saturday. Because if you remove the commit that contains the .env from the commit history it will cause a domino effect of issues.

**Review by Willi86 — CHANGES_REQUESTED** [review]
I'm getting this error :

Unhandled Runtime Error
Error: Text content does not match server-rendered HTML.
See more info here: https://nextjs.org/docs/messages/react-hydration-error

Text content did not match. Server: "Sign In" Client: "Profile"


<a>
  <p>
    "Sign In"
    "Profile"
    
image

**Comment by HannaRosberg** [comment]
This error have been all the time. But it haven't been in the way of the functionalities of the Web page. Everything have been working like it should anyway.

**Review by Willi86 — APPROVED** [review]
Considering your response i approved the request.

**Pull request merged**
